#!/bin/bash
if [ $(id -u) -eq 0 ]
then
	sleep 0.1s
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "solo root"
	echo "Su usuario no esta en sudo"
	echo -e "Para ser root ejecute \033[1;31msudo su\033[0m"
	exit
	else
	echo -e "no esta como usuario root, no puede leer sus directorios (sudo)\nPara ser root ejecute \033[1;31msu\033[0m y digite su contraseña root"
	exit
	fi
fi
verdee="\033[1;32m"
amareloo="\033[1;33m"
corPadrao="\033[0m"

touch /tmp/portas
if [ "$1" = "auto" ]; then
squidinstall="n"
echo -e "/bin/false" >> /etc/shells
else
while true; do
clear
echo -e "\033[1;31m
INSTALADOR DROPBEAR!
"
echo -e "\033[1;31m[ 1 ]\033[1;34m - DROPBEAR SIN PROXY SQUID3
\033[1;34m"
read -p "[1]: " opcao
case $opcao in
1)
squidinstall="n"
echo -e "/bin/false" >> /etc/shells
break
;;
2)
squidinstall="s"
echo -e "/bin/false" >> /etc/shells
break
;;
*)
echo -e "\033[1;31mOh, no a seleccionado una opcion Correta... Selecione opcion 1 o 1.\033[0m"
sleep 4s
;;
esac
done
fi
insta="1"
#INSTALACION#
if [ "$1" = "auto" ]; then
clear
echo "82%" > $HOME/instalação
sleep 0.5s
pts="80"
 else
echo -e "\033[1;31mDIGITE QUE PUERTO PRINCIPAL DESEA USAR, 443 ESTA ABIERTO! elija, 80,53,444,8080...\033[1;34m"
read -p "PUERTO: " -e -i 80 pts
if [ "$pts" = "" ]; then
porta="53"
else
 if [ "$pts" = "22" ]; then
echo -e "\033[1;31mPUERTO 22 DESTINADA PARA LA ADMINISTRACION DE SU VPS\033[0m"
porta="80"
 else
   if [ "$pts" = "443" ]; then
echo -e "\033[1;31mPUERTO 443 YA ABIERTO!\033[1;34m"
porta="80"
 else
porta="$pts"
     fi
   fi
 fi
fi
echo "$porta" >> /tmp/portas
echo "443" >> /tmp/portas

if [ "$1" = "auto" ]; then
opcao4="1"
 else
while true
do
clear
echo -e "$verdee
Que es su VPS? $corPadrao"
echo -e "$amareloo
 [1] Debian
 [2] Ubuntu $corPadrao"
read -p "OPCIÓN: " option4
case $option4 in
1)
opcao4="1"
break
;;
2)
opcao4="2"
break
;;
esac
done
fi

sleep 2s
if [ "$opcao4" = "1" ]; then
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
echo "Instalando dropbear"
apt-get install dropbear -y 1>/dev/null 2>/dev/null
touch /etc/dropbear/banner
sleep 2s
echo "Configurando dropbear"
printf "#loading\nNO_START=0\nDROPBEAR_PORT=$porta\n" > /etc/default/dropbear
echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
sleep 2s
echo "Su dropbear fue configurado con exito"
sleep 2s
echo -e "$verdee"
  if [[ "$squidinstall" = 's' ]]; then
sleep 2s
echo -e "\033[0m"
echo -e "\033[1;33mIniciando Instalacion Squid3\033[0m"
sleep 3s
sq3
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
  else
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
 fi
fi

if [ "$opcao4" = "2" ]; then
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
echo "Instalando dropbear"
apt-get install dropbear -y 1>/dev/null 2>/dev/null
touch /etc/dropbear/banner
sleep 2s
echo "Configurando dropbear"
printf "#loading\nNO_START=0\nDROPBEAR_PORT=$porta\n" > /etc/default/dropbear
echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
sleep 2s
echo "Su dropbear fue configurado con éxito"
sleep 2s
echo -e "$verdee"
  if [[ "$squidinstall" = 's' ]]; then
echo -e "\033[1;33mIniciando Instalación Squid\033[0m"
sleep 3s
sq3
echo -e "$verdee"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
echo "Saliendo..."
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
  else
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
echo "Saliendo..."
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
 fi
fi
if [ "$1" = "auto" ]; then
echo "90%" > $HOME/instalação
fi
exit
